---
title: "Exploração dos Modelos"
date: "Outubro de 2019"
---

```{r setup_evaluation, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos =  "h")
knitr::opts_knit$set(root.dir = "./")

# loading required libraries
library(dplyr)
library(forecast)
library(lubridate)
library(readxl)
library(knitr)
```

```{r scripts_evaluation, include=FALSE}
# loading required steps before performing the analysis
source("../src/util/auxiliary_functions.R")
ClearEnvironment()
```

# Criando os datasets de séries temporais

## Carregando a base de dados processada

```{r data_load, echo=TRUE}
target_data <- readRDS('../data/processed/target_dataset.rds')

target_ts <- ts(target_data$Sales, 
                start = c(2005,1), 
                end = c(2010, 4), 
                frequency = 4)

summary(target_ts)
```

## Criando o conjunto de dados de treino e teste

```{r create_train_test_datasets, echo=TRUE, out.width= '100%'}
# creating train and test sets ------------------------------------------------
GenerateTrainTestDatasets(target_ts,
                          c(2005, 1),
                          c(2009, 4),
                          c(2010, 1),
                          c(2010, 4))

train_ts <- readRDS('../data/processed/train_ts.rds')
test_ts  <- readRDS('../data/processed/test_ts.rds')

# plot of the training and testing temporal series
plot(train_ts, 
     xlab = "Tempo", 
     ylab = "Vendas", 
     xaxt = "n", 
     ylim = c(48000, 104000), 
     xlim = c(2005, 2011), 
     bty = "l")
axis(1, at = seq(2005, 2011, 1), labels = format(seq(2005, 2011, 1)))
lines(test_ts, bty = "l", col = "red")
box(lty = '1373', col = 'black')
```

*******************************************************************************

# Rodando os modelos lineares de séries temporais

Chamando a função de geração dos modelos lineares

```{r generating_linear_models, echo=TRUE, out.width= '100%'}
consolidation <- GenerateLinearTimeSeriesModels(train_ts, test_ts)
kable(consolidation)
```

## Analisando os resultados do modelo de Tendência Linear

```{r run_linear_time_series_model_1, echo=TRUE, out.width= '100%'}
#to-do
```


*******************************************************************************

# Considerações finais

To-do.
