---
title: "Conclusion"
date: "October, 2019"
---

```{r setup_evaluation, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos =  "h")
knitr::opts_knit$set(root.dir = "../")

# loading required libraries
library(forecast)
library(lubridate)
library(readxl)
library(crayon)
```

```{r scripts_evaluation, include=FALSE}
# loading required steps before performing the analysis
source("../src/util/auxiliary_functions.R")
```

# Objective

Describe the objetive of this report.

*******************************************************************************

# Models evaluation

## Getting the MAPE score from each model

```{r get_scores_evaluation, echo=TRUE}

target_data <- readRDS('../data/processed/target_dataset.rds')

target_ts <- ts(target_data$Sales, 
                start = c(2005,1), 
                end = c(2010, 4), 
                frequency = 4)


```

## Getting performance measures for each model.

```{r get_measures_evaluation, echo=TRUE, out.width= '100%'}
## getting cut off measures -----------------------------------------------------------------
# your code goes here
```

*******************************************************************************

# Final considerations and project limitations

To-do.